PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/28d7061550e41a73fdaa3802e515be077dd14f32

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...28d7061550e41a73fdaa3802e515be077dd14f32

28d7061550 (HEAD, origin/master) boards: stm32f4discovery: Modify a default path to a romfs image because the stm32f4discovery directory has been moved from configs/ to boards/arm/stm32/
c4c0d05891 arch/arm/src/imxrt; Adds clock config logic and Kconfig menus for FLEXIO on IMXRT
3c0b49448a Network Loopback Driver:  A configuration option to control packet size.
2af17da334 boards/sim:  Add a TCP loopback test.
ac4e6618bb arch/mips: Clear the software interrupt through a common function implemented in the chip specific code.
90043390ff arch/mips/: Fix architectures' references in Kconfigs and Toolchain.defs.
0dc1dc605d arch/mips: When a CPU implements an External Interrupt Controller, use the IPL bits to control masking interrupts.
d68693f74c drivers/telnet: Stop the loop if SIGSTP char is match and SIGINT not enabled
7ec66ccf94 Get the full directory name of the testbuild.sh no matter where called from
d09af3b7f3 Run .c and .h files modified by PR241 through nxstyle.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

44b8c9c5 (HEAD -> master, origin/master) apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m